INSERT INTO "Customer_Success" (
    deployment_id,
    account_name,
    customer_stage,
    account_owner,
    annual_recurring_revenue,
    technical_account_manager,
    last_engagement_date,
    sast,
    ssc,
    secrets,
    active_contributors_count,
    health_color,
    latest_contract_end_date,
    open_critical_feature_request,
    days_since_last_contact,
    license_expiration_date,
    total_contributors,
    contributors_last_30_days,
    insert_time
) VALUES
(
    'dep-acme-001',
    'Acme Corp',
    'Active',
    'owner-acme@example.com',
    245000.00,
    'tam-acme@example.com',
    '2026-02-07',
    TRUE,
    TRUE,
    TRUE,
    34,
    'Green',
    '2027-01-31',
    0,
    6,
    '2027-01-31',
    112,
    18,
    CURRENT_TIMESTAMP
),
(
    'dep-globex-014',
    'Globex Inc',
    'Onboarding',
    'owner-globex@example.com',
    98000.00,
    'tam-globex@example.com',
    '2026-01-29',
    TRUE,
    FALSE,
    FALSE,
    12,
    'Yellow',
    '2026-11-30',
    1,
    15,
    '2026-11-30',
    47,
    9,
    CURRENT_TIMESTAMP
),
(
    'dep-initech-109',
    'Initech',
    'Renewal',
    'owner-initech@example.com',
    152500.00,
    'tam-initech@example.com',
    '2025-12-18',
    FALSE,
    TRUE,
    FALSE,
    7,
    'Red',
    '2026-03-15',
    3,
    57,
    '2026-03-15',
    25,
    4,
    CURRENT_TIMESTAMP
) ON CONFLICT (deployment_id) DO UPDATE SET
    account_name = EXCLUDED.account_name,
    customer_stage = EXCLUDED.customer_stage,
    account_owner = EXCLUDED.account_owner,
    annual_recurring_revenue = EXCLUDED.annual_recurring_revenue,
    technical_account_manager = EXCLUDED.technical_account_manager,
    last_engagement_date = EXCLUDED.last_engagement_date,
    sast = EXCLUDED.sast,
    ssc = EXCLUDED.ssc,
    secrets = EXCLUDED.secrets,
    active_contributors_count = EXCLUDED.active_contributors_count,
    health_color = EXCLUDED.health_color,
    latest_contract_end_date = EXCLUDED.latest_contract_end_date,
    open_critical_feature_request = EXCLUDED.open_critical_feature_request,
    days_since_last_contact = EXCLUDED.days_since_last_contact,
    license_expiration_date = EXCLUDED.license_expiration_date,
    total_contributors = EXCLUDED.total_contributors,
    contributors_last_30_days = EXCLUDED.contributors_last_30_days,
    insert_time = EXCLUDED.insert_time;

INSERT INTO feature_request (
    case_number,
    case_owner,
    account_name,
    subject,
    status,
    opportunity,
    feature_request,
    linear_url_fr,
    date_time_opened,
    priority,
    open,
    closed,
    technical_account_manager,
    feature_request_status,
    insert_time
) VALUES
(
    'FR-0001',
    'owner-acme@example.com',
    'Acme Corp',
    'Add SAML support',
    'Open',
    'Renewal',
    'SAML enterprise login',
    'https://linear.app/acme/issue/FR-1',
    '2026-01-10',
    'P1',
    TRUE,
    FALSE,
    'tam-acme@example.com',
    'In progress',
    CURRENT_TIMESTAMP
),
(
    'FR-0002',
    'owner-globex@example.com',
    'Globex Inc',
    'Improve dashboard performance',
    'Open',
    'Expansion',
    'Faster dashboard loading',
    'https://linear.app/globex/issue/FR-2',
    '2026-01-22',
    'P0',
    TRUE,
    FALSE,
    'tam-globex@example.com',
    'Planned',
    CURRENT_TIMESTAMP
),
(
    'FR-0003',
    'owner-initech@example.com',
    'Initech',
    'Export trends as CSV',
    'Closed',
    'None',
    'CSV export for trends',
    NULL,
    '2025-12-12',
    'P2',
    FALSE,
    TRUE,
    'tam-initech@example.com',
    'Done',
    CURRENT_TIMESTAMP
) ON CONFLICT (case_number) DO UPDATE SET
    case_owner = EXCLUDED.case_owner,
    account_name = EXCLUDED.account_name,
    subject = EXCLUDED.subject,
    status = EXCLUDED.status,
    opportunity = EXCLUDED.opportunity,
    feature_request = EXCLUDED.feature_request,
    linear_url_fr = EXCLUDED.linear_url_fr,
    date_time_opened = EXCLUDED.date_time_opened,
    priority = EXCLUDED.priority,
    open = EXCLUDED.open,
    closed = EXCLUDED.closed,
    technical_account_manager = EXCLUDED.technical_account_manager,
    feature_request_status = EXCLUDED.feature_request_status,
    insert_time = EXCLUDED.insert_time;
